export const GET_ACCESSTOKEN = 'GET_ACCESSTOKEN';
export const CHECK_LOGININFO = 'CHECK_LOGININFO';
export const GET_NOTIFYMESSAGE = 'GET_NOTIFYMESSAGE';
export const GET_LOCALSTORAGE = 'GET_LOCALSTORAGE'; 